module Home exposing (..)

import Authenticator.Model
import Html exposing (a, br, button, div, footer, h1, h2, h3, h4, Html, img, input, label, li, p, span, text, ul)
import Html.Attributes exposing (alt, attribute, class, href, id, name, src, type', value)


-- MODEL


type alias Model =
    {}


init : Model
init =
    {}



-- UPDATE


type ExternalMsg
    = Navigate String


type InternalMsg
    = Todo


type Msg
    = ForParent ExternalMsg
    | ForSelf InternalMsg


type alias MsgTranslation parentMsg =
    { onInternalMsg : InternalMsg -> parentMsg
    , onNavigate : String -> parentMsg
    }


type alias MsgTranslator parentMsg =
    Msg -> parentMsg


navigate : String -> Msg
navigate path =
    ForParent (Navigate path)


translateMsg : MsgTranslation parentMsg -> MsgTranslator parentMsg
translateMsg { onInternalMsg, onNavigate } msg =
    case msg of
        ForParent (Navigate path) ->
            onNavigate path

        ForSelf internalMsg ->
            onInternalMsg internalMsg


update : InternalMsg -> Maybe Authenticator.Model.Authentication -> Model -> ( Model, Cmd Msg )
update msg authenticationMaybe model =
    case msg of
        Todo ->
            ( model, Cmd.none )



-- VIEW


view : Maybe Authenticator.Model.Authentication -> Model -> Html Msg
view authenticationMaybe model =
    div []
        [ viewBanner authenticationMaybe model
        , viewMetrics authenticationMaybe model
        , viewExamples authenticationMaybe model
        , viewTools authenticationMaybe model
        , viewOrganizations authenticationMaybe model
        , viewFooter authenticationMaybe model
        ]


viewBanner : Maybe Authenticator.Model.Authentication -> Model -> Html Msg
viewBanner authenticationMaybe model =
    div [ class "banner" ]
        [ div [ class "row " ]
            [ div [ class "carousel slide ", attribute "data-ride" "", id "carousel-example-generic" ]
                [ div [ class "carousel-inner ", attribute "role" "listbox" ]
                    [ div [ class "item active" ]
                        [ div [ class "jumbotron" ]
                            [ div [ class "container" ]
                                [ h1 []
                                    [ text "Find digital tools"
                                    , br []
                                        []
                                    , text "to improve democracy"
                                    ]
                                , a [ class "btn btn-primary btn-lg", attribute "data-slide-to" "1", href "#carousel-example-generic", attribute "role" "button" ]
                                    [ text "Start browsing" ]
                                ]
                            ]
                        , div [ class "carousel-caption" ]
                            []
                        ]
                    , div [ class "item text-center" ]
                        [ div [ class "container" ]
                            [ div [ class "row" ]
                                [ div [ class "col-md-12 text-center" ]
                                    [ img [ src "img/bubbles.png" ]
                                        []
                                    ]
                                ]
                            , div [ class "row filters" ]
                                [ div [ class "col-md-12 text-center" ]
                                    [ text "Showing results suited for                  "
                                    , div [ class "dropdown dropdown-filter dropup" ]
                                        [ a [ class "btn btn-default dropdown-toggle", attribute "data-slide-to" "2", href "#carousel-example-generic", attribute "role" "button" ]
                                            [ text "all organizations                      "
                                            , span [ class "caret" ]
                                                []
                                            ]
                                        , ul [ attribute "aria-labelledby" "dropdownMenu1", class "dropdown-menu" ]
                                            [ li []
                                                [ a [ href "#" ]
                                                    [ text "all organizations" ]
                                                ]
                                            , li []
                                                [ a [ href "#" ]
                                                    [ text "Local government" ]
                                                ]
                                            , li []
                                                [ a [ href "#" ]
                                                    [ text "Regional government" ]
                                                ]
                                            , li []
                                                [ a [ href "#" ]
                                                    [ text "National government" ]
                                                ]
                                            , li []
                                                [ a [ href "#" ]
                                                    [ text "Political organization" ]
                                                ]
                                            , li []
                                                [ a [ href "#" ]
                                                    [ text "Political movement" ]
                                                ]
                                            , li []
                                                [ a [ href "#" ]
                                                    [ text "Non-profit organization" ]
                                                ]
                                            , li []
                                                [ a [ href "#" ]
                                                    [ text "For-profit organization" ]
                                                ]
                                            ]
                                        ]
                                    , text "and available in                   "
                                    , div [ class "dropdown dropdown-filter dropup" ]
                                        [ a [ class "btn btn-default dropdown-toggle", attribute "data-slide-to" "3", href "#carousel-example-generic", attribute "role" "button" ]
                                            [ text "English                      "
                                            , span [ class "caret" ]
                                                []
                                            ]
                                        , ul [ attribute "aria-labelledby" "dropdownMenu1", class "dropdown-menu" ]
                                            [ li []
                                                [ a [ href "#" ]
                                                    [ text "Français" ]
                                                ]
                                            , li []
                                                [ a [ href "#" ]
                                                    [ text "Espanol" ]
                                                ]
                                            , li []
                                                [ a [ href "#" ]
                                                    [ text "Deutsch" ]
                                                ]
                                            , li []
                                                [ a [ href "#" ]
                                                    [ text "Italiano" ]
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    , div [ class "item text-center" ]
                        [ div [ class "container" ]
                            [ div [ class "row form-title" ]
                                [ div [ class "col-md-12 text-center " ]
                                    [ h2 []
                                        [ span [ attribute "aria-hidden" "true", class "glyphicon glyphicon-education" ]
                                            []
                                        , text "Which kind of organization are your intrested in ?"
                                        ]
                                    ]
                                ]
                            , div [ class "row form-content" ]
                                [ div [ class "col-md-3 text-center" ]
                                    [ div [ class "radio" ]
                                        [ label []
                                            [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "radio", value "option1" ]
                                                []
                                            , text "All organiations                    "
                                            ]
                                        ]
                                    ]
                                , div [ class "col-md-3 text-center" ]
                                    [ div [ class "radio" ]
                                        [ label []
                                            [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "radio", value "option1" ]
                                                []
                                            , text "Local government                    "
                                            ]
                                        ]
                                    ]
                                , div [ class "col-md-3 text-center" ]
                                    [ div [ class "radio" ]
                                        [ label []
                                            [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "radio", value "option1" ]
                                                []
                                            , text "Regional government                    "
                                            ]
                                        ]
                                    ]
                                , div [ class "col-md-3 text-center" ]
                                    [ div [ class "radio" ]
                                        [ label []
                                            [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "radio", value "option1" ]
                                                []
                                            , text "National government                    "
                                            ]
                                        ]
                                    ]
                                , div [ class "col-md-3 text-center" ]
                                    [ div [ class "radio" ]
                                        [ label []
                                            [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "radio", value "option1" ]
                                                []
                                            , text "Political organization                    "
                                            ]
                                        ]
                                    ]
                                , div [ class "col-md-3 text-center" ]
                                    [ div [ class "radio" ]
                                        [ label []
                                            [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "radio", value "option1" ]
                                                []
                                            , text "Political movement                    "
                                            ]
                                        ]
                                    ]
                                , div [ class "col-md-3 text-center" ]
                                    [ div [ class "radio" ]
                                        [ label []
                                            [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "radio", value "option1" ]
                                                []
                                            , text "Non-profit organization                    "
                                            ]
                                        ]
                                    ]
                                , div [ class "col-md-3 text-center" ]
                                    [ div [ class "radio" ]
                                        [ label []
                                            [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "radio", value "option1" ]
                                                []
                                            , text "For-profit organization                    "
                                            ]
                                        ]
                                    ]
                                ]
                            , div [ class "row" ]
                                [ div [ class "col-md-12 text-center" ]
                                    [ a [ class "btn btn-primary btn-lg", attribute "data-slide-to" "1", href "#carousel-example-generic", attribute "role" "button" ]
                                        [ text "Continue" ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                , div [ class "item text-center" ]
                    [ div [ class "container" ]
                        [ div [ class "row form-title" ]
                            [ div [ class "col-md-12 text-center " ]
                                [ h2 []
                                    [ span [ attribute "aria-hidden" "true", class "glyphicon glyphicon-globe" ]
                                        []
                                    , text "Which language do you use ?"
                                    ]
                                ]
                            ]
                        , div [ class "row form-content" ]
                            [ div [ class "col-md-3 text-center" ]
                                [ div [ class "checkbox" ]
                                    [ label []
                                        [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "checkbox", value "option1" ]
                                            []
                                        , text "English                    "
                                        ]
                                    ]
                                ]
                            , div [ class "col-md-3 text-center" ]
                                [ div [ class "checkbox" ]
                                    [ label []
                                        [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "checkbox", value "option1" ]
                                            []
                                        , text "Français                    "
                                        ]
                                    ]
                                ]
                            , div [ class "col-md-3 text-center" ]
                                [ div [ class "checkbox" ]
                                    [ label []
                                        [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "checkbox", value "option1" ]
                                            []
                                        , text "Espanol                    "
                                        ]
                                    ]
                                ]
                            , div [ class "col-md-3 text-center" ]
                                [ div [ class "checkbox" ]
                                    [ label []
                                        [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "checkbox", value "option1" ]
                                            []
                                        , text "Deutsch                    "
                                        ]
                                    ]
                                ]
                            , div [ class "col-md-3 text-center" ]
                                [ div [ class "checkbox" ]
                                    [ label []
                                        [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "checkbox", value "option1" ]
                                            []
                                        , text "Italian                    "
                                        ]
                                    ]
                                ]
                            , div [ class "col-md-3 text-center" ]
                                [ div [ class "checkbox" ]
                                    [ label []
                                        [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "checkbox", value "option1" ]
                                            []
                                        , text "Arab                    "
                                        ]
                                    ]
                                ]
                            , div [ class "col-md-3 text-center" ]
                                [ div [ class "checkbox" ]
                                    [ label []
                                        [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "checkbox", value "option1" ]
                                            []
                                        , text "Japanese                    "
                                        ]
                                    ]
                                ]
                            , div [ class "col-md-3 text-center" ]
                                [ div [ class "checkbox" ]
                                    [ label []
                                        [ input [ attribute "checked" "", id "optionsRadios1", name "optionsRadios", type' "radio", value "option1" ]
                                            []
                                        , text "Russian                    "
                                        ]
                                    ]
                                ]
                            ]
                        , div [ class "row" ]
                            [ div [ class "col-md-12 text-center" ]
                                [ a [ class "btn btn-primary btn-lg", attribute "data-slide-to" "1", href "#carousel-example-generic", attribute "role" "button" ]
                                    [ text "Continue" ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]


viewExamples : Maybe Authenticator.Model.Authentication -> Model -> Html Msg
viewExamples authenticationMaybe model =
    div [ class "row section" ]
        [ div [ class "container" ]
            [ h3 [ class "zone-label" ]
                [ text "Examples" ]
            , div [ class "row" ]
                [ div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail example grey" ]
                        [ div [ class "visual" ]
                            [ img [ alt "screen", src "img/screen1.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ div [ class "example-author-thumb" ]
                                [ img [ alt "screen", src "img/whitehouse.png" ]
                                    []
                                ]
                            , h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail example grey" ]
                        [ div [ class "visual" ]
                            [ img [ alt "screen", src "img/screen2.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ div [ class "example-author-thumb" ]
                                [ img [ alt "screen", src "img/hackpad.png" ]
                                    []
                                ]
                            , h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail example grey" ]
                        [ div [ class "visual" ]
                            [ img [ alt "screen", src "img/screen3.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ div [ class "example-author-thumb" ]
                                [ img [ alt "screen", src "img/whitehouse.png" ]
                                    []
                                ]
                            , h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail example grey" ]
                        [ div [ class "visual" ]
                            [ img [ alt "screen", src "img/screen4.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ div [ class "example-author-thumb" ]
                                [ img [ alt "screen", src "img/consul.png" ]
                                    []
                                ]
                            , h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail example grey" ]
                        [ div [ class "visual" ]
                            [ img [ alt "screen", src "img/screen1.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ div [ class "example-author-thumb" ]
                                [ img [ alt "screen", src "img/ckan.png" ]
                                    []
                                ]
                            , h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail example grey" ]
                        [ div [ class "visual" ]
                            [ img [ alt "screen", src "img/screen2.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ div [ class "example-author-thumb" ]
                                [ img [ alt "screen", src "img/whitehouse.png" ]
                                    []
                                ]
                            , h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail example grey" ]
                        [ div [ class "visual" ]
                            [ img [ alt "screen", src "img/screen3.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ div [ class "example-author-thumb" ]
                                [ img [ alt "screen", src "img/hackpad.png" ]
                                    []
                                ]
                            , h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail example grey" ]
                        [ div [ class "visual" ]
                            [ img [ alt "screen", src "img/screen4.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ div [ class "example-author-thumb" ]
                                [ img [ alt "screen", src "img/whitehouse.png" ]
                                    []
                                ]
                            , h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-sm-12 text-center" ]
                    [ a [ class "show-more" ]
                        [ text "Show all 398"
                        , span [ class "glyphicon glyphicon-menu-down" ]
                            []
                        ]
                    ]
                ]
            ]
        ]


viewFooter : Maybe Authenticator.Model.Authentication -> Model -> Html Msg
viewFooter authenticationMaybe model =
    footer []
        [ div [ class "row section footer" ]
            [ div [ class "container" ]
                [ div [ class "row" ]
                    [ div [ class "col-xs-12 col-md-6" ]
                        [ div [ class "row" ]
                            [ div [ class "col-xs-6" ]
                                [ img [ alt "Toolname", class "footer-logo", src "img/ogp-logo.png" ]
                                    []
                                ]
                            , div [ class "col-xs-6" ]
                                [ h4 []
                                    [ text "Language" ]
                                , div [ class "dropdown dropdown-language" ]
                                    [ button [ attribute "aria-expanded" "true", attribute "aria-haspopup" "true", class "btn btn-default dropdown-toggle", attribute "data-toggle" "dropdown", id "dropdownMenu1", type' "button" ]
                                        [ text "English                  "
                                        , span [ class "caret" ]
                                            []
                                        ]
                                    , ul [ attribute "aria-labelledby" "dropdownMenu1", class "dropdown-menu" ]
                                        [ li []
                                            [ a [ href "#" ]
                                                [ text "Français" ]
                                            ]
                                        , li []
                                            [ a [ href "#" ]
                                                [ text "Espanol" ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        , p [ class "info-box" ]
                            [ text "The Open Government Partnership is a multilateral initiative that aims to secure concrete commitments from governments to promote transparency, empower citizens, fight corruption, and harness new technologies to strengthen governance. In the spirit of multi-stakeholder collaboration, OGP is overseen by a Steering Committee including representatives of governments and civil society organizations." ]
                        ]
                    , div [ class "col-xs-6 col-md-3" ]
                        [ h4 []
                            [ text "About" ]
                        , ul [ class "footer-menu" ]
                            [ li []
                                [ a [ href "#" ]
                                    [ text "Eligibility Criteria" ]
                                ]
                            , li []
                                [ a [ href "#" ]
                                    [ text "Develop a National Action Plan" ]
                                ]
                            , li []
                                [ a [ href "#" ]
                                    [ text "Self-Assessment Process" ]
                                ]
                            , li []
                                [ a [ href "#" ]
                                    [ text "Response Policy" ]
                                ]
                            , li []
                                [ a [ href "#" ]
                                    [ text "Civil Society Engagement" ]
                                ]
                            , li []
                                [ a [ href "#" ]
                                    [ text "Calendars and Deadlines" ]
                                ]
                            ]
                        ]
                    , div [ class "col-xs-6 col-md-3" ]
                        [ h4 []
                            [ text "How it works" ]
                        , ul [ class "footer-menu" ]
                            [ li []
                                [ a [ href "#" ]
                                    [ text "Home" ]
                                ]
                            , li []
                                [ a [ href "#" ]
                                    [ text "Profile" ]
                                ]
                            , li []
                                [ a [ href "#" ]
                                    [ text "Messages" ]
                                ]
                            ]
                        ]
                    ]
                , div [ class "row copyright" ]
                    [ div [ class "col-md-12" ]
                        [ text "© 2016 Open Government Partnership" ]
                    ]
                ]
            ]
        ]


viewMetrics : Maybe Authenticator.Model.Authentication -> Model -> Html Msg
viewMetrics authenticationMaybe model =
    div [ class "row metrics" ]
        [ div [ class "container" ]
            [ div [ class "col-xs-4 text-center" ]
                [ span [ class "metric-label" ]
                    [ text "Examples" ]
                , h3 []
                    [ text "5891" ]
                ]
            , div [ class "col-xs-4 text-center" ]
                [ span [ class "metric-label" ]
                    [ text "Tools" ]
                , h3 []
                    [ text "318" ]
                ]
            , div [ class "col-xs-4 text-center" ]
                [ span [ class "metric-label" ]
                    [ text "Organizations" ]
                , h3 []
                    [ text "127" ]
                ]
            ]
        ]


viewOrganizations : Maybe Authenticator.Model.Authentication -> Model -> Html Msg
viewOrganizations authenticationMaybe model =
    div [ class "row section" ]
        [ div [ class "container" ]
            [ h3 [ class "zone-label" ]
                [ text "Organizations" ]
            , div [ class "row" ]
                [ div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail orga grey" ]
                        [ div [ class "visual" ]
                            [ img [ alt "logo", src "img/hackpad.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ h4 []
                                [ text "The White House" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail orga grey" ]
                        [ div [ class "visual" ]
                            [ img [ alt "logo", src "img/whitehouse.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ h4 []
                                [ text "The White House" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail orga grey" ]
                        [ div [ class "visual" ]
                            [ img [ alt "logo", src "img/hackpad.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ h4 []
                                [ text "The White House" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail orga grey" ]
                        [ div [ class "visual" ]
                            [ img [ alt "logo", src "img/hackpad.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ h4 []
                                [ text "The White House" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            ]
                        ]
                    ]
                , div [ class "col-sm-12 text-center" ]
                    [ a [ class "show-more" ]
                        [ text "Show all 398"
                        , span [ class "glyphicon glyphicon-menu-down" ]
                            []
                        ]
                    ]
                ]
            ]
        ]


viewTools : Maybe Authenticator.Model.Authentication -> Model -> Html Msg
viewTools authenticationMaybe model =
    div [ class "row section grey" ]
        [ div [ class "container" ]
            [ h3 [ class "zone-label" ]
                [ text "Tools" ]
            , div [ class "row" ]
                [ div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail tool" ]
                        [ div [ class "visual" ]
                            [ img [ alt "logo", src "img/hackpad.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail tool" ]
                        [ div [ class "visual" ]
                            [ img [ alt "logo", src "img/ckan.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail tool" ]
                        [ div [ class "visual" ]
                            [ img [ alt "logo", src "img/consul.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail tool" ]
                        [ div [ class "visual" ]
                            [ img [ alt "logo", src "img/ckan.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail tool" ]
                        [ div [ class "visual" ]
                            [ img [ alt "logo", src "img/consul.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail tool" ]
                        [ div [ class "visual" ]
                            [ img [ alt "logo", src "img/tool.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail tool" ]
                        [ div [ class "visual" ]
                            [ img [ alt "Toolname", src "img/hackpad.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-xs-6 col-md-3 " ]
                    [ div [ class "thumbnail tool" ]
                        [ div [ class "visual" ]
                            [ img [ alt "Toolname", src "img/tool.png" ]
                                []
                            ]
                        , div [ class "caption" ]
                            [ h4 []
                                [ text "OpenSpending" ]
                            , p []
                                [ text "OpenSpending is a centralized platform on the topic of public financial information, including an global database of budgets and spending data, a community of contributors and users exposing cases, and a set of open resources and tools providing technical, fiscal, and political understanding necessary to work with financial data." ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            , span [ class "label label-default label-tool" ]
                                [ text "Default" ]
                            ]
                        ]
                    ]
                , div [ class "col-sm-12 text-center" ]
                    [ a [ class "show-more" ]
                        [ text "Show all 398"
                        , span [ class "glyphicon glyphicon-menu-down" ]
                            []
                        ]
                    ]
                ]
            ]
        ]
