module Press exposing (..)

import Html exposing (..)
import Html.Attributes exposing (..)
import I18n


view : I18n.Language -> Html msg
view language =
    div []
        [ header []
            [ div [ class "container" ]
                [ div [ class "intro-text" ]
                    [ div [ class "intro-heading" ]
                        [ text (I18n.translate language (I18n.Press)) ]
                    , div [ class "intro-lead-in" ]
                        [ text (I18n.translate language (I18n.PressLead)) ]
                    ]
                ]
            ]
        , section [ id "links", class "bg-light-gray" ]
            [ div [ class "container" ]
                [ div [ class "row" ]
                    [ div [ class "col-lg-12 text-center" ]
                        [ h2 [ class "section-heading" ]
                            [ text "Liens utiles" ]
                        ]
                    ]
                , div [ class "row" ]
                    [ div [ class "col-md-12" ]
                        [ p []
                            [ a [ href "http://www.twitter.com/ogptoolbox" ]
                                [ strong [] [ text "Compte Twitter officiel" ] ]
                            ]
                        ]
                    ]
                , div [ class "row" ]
                    [ div [ class "col-md-12 col-sm-6" ]
                        [ p []
                            [ a [ href "https://forum.etalab.gouv.fr/c/gouvernement-ouvert/ogp-toolbox" ]
                                [ strong [] [ text "Forum" ] ]
                            ]
                        ]
                    ]
                ]
            ]
        , section [ id "articles" ]
            [ div [ class "container" ]
                [ div [ class "row" ]
                    [ div [ class "col-lg-12 text-center" ]
                        [ h2 [ class "section-heading" ]
                            [ text "Articles de presse" ]
                        ]
                    ]
                , div [ class "row" ]
                    [ div [ class "col-md-12 col-sm-6" ]
                        [ img [ src "/img/Press/lemonde.png" ] []
                        , strong [] [ text "Claire Legros pour Le Monde" ]
                        , br [] []
                        , a [ href "http://www.lemonde.fr/pixels/article/2016/10/25/civic-tech-vers-une-boite-a-outils-de-la-democratie-numerique_5019800_4408996.html" ]
                                [ strong [] [ text "« Civic Tech » : vers une boîte à outils de la démocratie numérique" ] ]
                        ]
                    ]
                , div [ class "row" ]
                    [ div [ class "col-md-12 col-sm-6" ]
                        [ strong [] [ text "AFP" ]
                        , p []
                            [ a [ href "http://www.notretemps.com/internet/gouvernement-ouvert-une-boite-a,i129914" ]
                                [ strong [] [ text "Gouvernement ouvert : une \"boîte à outils\" numériques mise à disposition des administrations" ] ]
                            ]
                        ]
                    ]
                , div [ class "row" ]
                    [ div [ class "col-md-12 col-sm-6" ]
                        [ strong [] [ text "Joinup " ]
                        , b []
                            [ a [ href "https://joinup.ec.europa.eu/community/opengov/news/france-develop-toolbox-open-government" ]
                                [ strong [] [ text "France to develop a toolbox for Open Government" ] ]
                            ]
                        ]
                    ]
                ]
              ]
        , section [ id "videos", class "bg-light-gray" ]
            [ div [ class "container" ]
                [ div [ class "row" ]
                    [ div [ class "col-lg-12 text-center" ]
                        [ h2 [ class "section-heading" ]
                            [ text "Vidéos" ]
                        ]
                    ]
                , div [ class "row" ]
                    [ div [ class "col-md-12 col-sm-6" ]
                        [ strong [] [ text "Elysée" ]
                        , p []
                            [ a [ href "https://www.dailymotion.com/video/x54m9l3_reportage-retour-sur-le-hackathon-a-l-elysee-dans-le-cadre-du-sommet-mondial-du-partenariat-pour-un_news" ]
                                [ strong [] [ text "Retour sur le hackathon à l'Élysée, dans le cadre du Sommet mondial du Partenariat pour un Gouvernement Ouvert " ] ]
                            ]
                        ]
                    ]
                , div [ class "row" ]
                    [ div [ class "col-md-12 col-sm-6" ]
                        [ strong [] [ text "V2" ]
                        , p []
                            [ a [ href "http://www.acteurspublics.tv/play/43555/paulaforteza" ]
                                [ strong [] [ text "Vidéo 2" ] ]
                            ]
                        ]
                    ]
                , div [ class "row" ]
                    [ div [ class "col-md-12 col-sm-6" ]
                        [ strong [] [ text "V3 " ]
                        , b []
                            [ a [ href "https://www.youtube.com/watch?v=_3w69Fzvv8I" ]
                                [ strong [] [ text "Vidéo 3" ] ]
                            ]
                        ]
                    ]
                ]
              ]
            ]
